In [81]:
import tensorflow as tf
import pandas as pd

In [82]:
print(tf.__version__)

2.6.0


In [83]:
a = tf.constant(5)
b = tf.constant(2)
c = tf.constant(3)

d = tf.multiply(a,b) 
e = tf.add(c,b)
f = tf.subtract(d,e) 

print("add_result = {}".format(e))
print("multiply_result = {}".format(d))
print("subtract_result = {}".format(f))

add_result = 5
multiply_result = 10
subtract_result = 5


In [84]:
## tensorflow로 (5*2) - (3+2) 연산을 수행하기
# 1. tf.constant로 상수 선언해서 연산 수행하기
# 2. tf.Variable로 상수 선언해서 연산 수행하기

a = tf.Variable(5)
b = tf.Variable(2)
c = tf.Variable(3)

d = tf.multiply(a,b) 
e = tf.add(c,b)
f = tf.subtract(d,e) 

print("add_result = {}".format(e))
print("multiply_result = {}".format(d))
print("subtract_result = {}".format(f))

add_result = 5
multiply_result = 10
subtract_result = 5


In [85]:
import numpy as np

a = tf.Variable(5)
b = np.array(3)
c = tf.Variable(2)

d = tf.multiply(a,b) 
e = tf.add(c,b)
f = tf.subtract(d,e) 

print("add_result = {}".format(e))
print("multiply_result = {}".format(d))
print("subtract_result = {}".format(f))

add_result = 5
multiply_result = 15
subtract_result = 10


In [86]:
x = tf.Variable(0)

# for 문
for i in range(1,11):
  x = x + i
  print("Value : {}".format(x))

print("total_sum : {}".format(x))

Value : 1
Value : 3
Value : 6
Value : 10
Value : 15
Value : 21
Value : 28
Value : 36
Value : 45
Value : 55
total_sum : 55


In [87]:
a = tf.Variable(tf.random.normal((1,1), mean = 0, stddev=1.0))
b = tf.Variable(tf.random.normal((1,1), mean = 0, stddev=1.0))
c = tf.Variable(tf.random.normal((1,1), mean = 0, stddev=1.0))

d = tf.multiply(a,b) 
e = tf.add(c,b)
f = tf.subtract(d,e) 

print("add_result = {}".format(e))
print("multiply_result = {}".format(d))
print("subtract_result = {}".format(f))

add_result = [[0.74089384]]
multiply_result = [[0.20737752]]
subtract_result = [[-0.5335163]]


In [88]:
# 다차원 변수

x1 = tf.Variable([[1,2], [3,4], [5,6], [7,8], [9,10]])

print("x1 = {}".format(x1))
print("x1 = {}".format(x1.shape))

x1 = <tf.Variable 'Variable:0' shape=(5, 2) dtype=int32, numpy=
array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]], dtype=int32)>
x1 = (5, 2)


In [89]:
x1_reshape = tf.reshape(x1, [2,5])

print("x1 = {}".format(x1_reshape))
print("x1 = {}".format(x1_reshape.shape))

x1 = [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
x1 = (2, 5)


In [90]:
## Step2 tensorflow matrix operation

In [91]:
### scalar
scalar_A =tf.constant(1)
scalar_B =tf.constant(1)
add_scalar_AB= scalar_A+scalar_B
## 1-dim
vector_A =tf.constant([1, 2, 3])
vector_B =tf.constant([3, 5, 7])
add_vector_AB= vector_A + vector_B
## 2-dim
matrix_A = tf.constant([[1, 2],
[3, 4]])
matrix_B = tf.constant([[4, 3],
[2, 1]])
matrix_AB = tf.matmul(matrix_A, matrix_B)
print(matrix_AB)

tf.Tensor(
[[ 8  5]
 [20 13]], shape=(2, 2), dtype=int32)


In [92]:
A = tf.constant([[2,2,4],
                 [1,1,6],
                 [1,3,8]])

B = tf.constant([[4,3,3],
                 [2,1,6],
                 [1,2,8]])

AB = tf.matmul(A, B)

print("result = {}".format(AB))
print(AB.shape)

result = [[16 16 50]
 [12 16 57]
 [18 22 85]]
(3, 3)


### Perceptron 작성

In [99]:

import tensorflow as tf

## data 선언
x_data =[[1.],[2.],[3.],[4.]]
y_data =[[1.],[3.],[5.],[7.]]

print(x_data)
print(y_data)

[[1.0], [2.0], [3.0], [4.0]]
[[1.0], [3.0], [5.0], [7.0]]


In [105]:
## 평균 0, 분산 1의 파라미터의 정규분포로 부터 값을 가져옴.
# 학습을 통해 업데이트가 되어 변화되는 모델의 파라미터인 w,b를 의미한다.
W= tf.Variable(tf.random.normal((1,1), mean = 0, stddev=1.0))  
b= tf.Variable(tf.random.normal((1,1), mean = 0, stddev=1.0))
print("W : {}".format(W))
print("b : {}".format(b))


W : <tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[0.43925336]], dtype=float32)>
b : <tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[-1.909583]], dtype=float32)>


In [106]:
for j in range(len(x_data)):
    ## data * weight 작성
    WX = tf.matmul([x_data[j]], W)

    ## bias add 작성
    y_hat = tf.add(WX , b)

    ## W와 b로 예측 하기
    print("y_data: , ",y_data[j], "prediction : ", y_hat)

y_data: ,  [1.0] prediction :  tf.Tensor([[-1.4703296]], shape=(1, 1), dtype=float32)
y_data: ,  [3.0] prediction :  tf.Tensor([[-1.0310762]], shape=(1, 1), dtype=float32)
y_data: ,  [5.0] prediction :  tf.Tensor([[-0.59182286]], shape=(1, 1), dtype=float32)
y_data: ,  [7.0] prediction :  tf.Tensor([[-0.15256953]], shape=(1, 1), dtype=float32)


# Tensorflow Linear Regression

In [109]:
import tensorflow as tf

## data 선언
x_data =[[1.],[2.],[3.],[4.]]
y_data =[[1.],[3.],[5.],[7.]]



In [111]:
## 평균 0, 분산 1의 파라미터의 정규분포로 부터 값을 가져옴.
# 학습을 통해 업데이트가 되어 변화되는 모델의 파라미터인 w,b를 의미한다.
W=tf.Variable(tf.random.normal((1,1),mean=0, stddev=1.0))
b=tf.Variable(tf.random.normal((1,1),mean=0, stddev=1.0))
lr=tf.constant(0.0001) # 보폭
history = np.zeros([2000, 4], 'float32')

In [113]:

for i in range(2000):  ## 에폭(전체 데이터를 몇 번 볼거냐)
    total_error = 0

    for j in range(len(x_data)): ## 배치 1(전체 데이터를 몇 개 씩 나눠 볼거냐)
        ## data * weight
        WX =tf.matmul([x_data[j]], W) ## [1.] * [1X1 : w:init]

        ## bias add
        y_hat = tf.add(WX, b) ## y= wx + b

        ## 정답인 Y와 출력값의 error 계산
        error = tf.subtract(y_data[j], y_hat) # true - prediction

        ## 경사하강법으로 W와 b 업데이트.
        ## 도함수 구하기 
        diff_W = tf.matmul(error, [x_data[j]]) # error * x의 합
        diff_b = error

        ##  업데이트할 만큼 러닝레이트 곱
        diff_W = tf.multiply(lr, diff_W)
        diff_b = tf.multiply(lr, diff_b) # lr * error

        ## w, b 업데이트
        W = tf.add(W, diff_W) # W + delta w + lr * x * (error)
        b = tf.add(b, diff_b) # b + delta b + lr * (error)
        #######

        ## 토탈 에러.
        visual_error = tf.square(error)
        total_error = total_error + visual_error

    ## 모든 데이터에 따른 error 값
    print("epoch: ", i, "error : ", total_error/len(x_data))
    history[i,:] = [(total_error/len(x_data))[0], W[0], b[0]]

epoch:  0 error :  tf.Tensor([[90.3035]], shape=(1, 1), dtype=float32)


ValueError: ignored

In [ ]:
## 학습끝난 후 W와 b로 예측 하기
print(history)
print("W : ", W)
print("b : ", b)
print("input 3 : ", tf.add(tf.multiply(3, W), b))
print("input 5 : ", tf.add(tf.multiply(5, W), b))

In [ ]:
## 
x_data = [[2,0], [4,4], [6,2], [8,3]]
y_data = [[81], [93], [91], [97]]
test_data = [[5.,5.]]
print(len(x_data),len(x_data[1])) # 행크기, 열크기

# Tensorflow Keras

In [122]:
import tensorflow as tf

x_data =[[1.],[2.],[3.],[4.]]
y_data =[[1.],[3.],[5.],[7.]]

test_data = [[9.]]

In [123]:
model = tf.keras.Sequential()

model.add(tf.keras.layers.Dense(1, input_dim=1))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1)                 2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [116]:
optimizer = tf.keras.optimizers.SGD(lr=0.01) # 경사하강법 global min 찾아가는 최적의 방법
loss = tf.keras.losses.mse # 예측한 값과 정답간 오차를 계산. mse = mean square error (예측값 - 정답)^2
metrics = tf.keras.metrics.mae # mae = mean absolute error |예측값 - 정답| 

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/optimizer_v2.py:356: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")


In [125]:
# 모델 컴파일
model.compile(loss='mse', optimizer=optimizer, metrics=[metrics])

model.fit(x_data, y_data, epochs=2000, batch_size=1)

Epoch 1/2000
4/4 [==============================] - 0s 3ms/step - loss: 3.8340 - mean_absolute_error: 1.5630
Epoch 2/2000
4/4 [==============================] - 0s 2ms/step - loss: 1.0401 - mean_absolute_error: 0.8807
Epoch 3/2000
4/4 [==============================] - 0s 3ms/step - loss: 0.4068 - mean_absolute_error: 0.5390
Epoch 4/2000
4/4 [==============================] - 0s 3ms/step - loss: 0.2881 - mean_absolute_error: 0.4801
Epoch 5/2000
4/4 [==============================] - 0s 3ms/step - loss: 0.2621 - mean_absolute_error: 0.4397
Epoch 6/2000
4/4 [==============================] - 0s 3ms/step - loss: 0.2562 - mean_absolute_error: 0.4245
Epoch 7/2000
4/4 [==============================] - 0s 3ms/step - loss: 0.2494 - mean_absolute_error: 0.4273
Epoch 8/2000
4/4 [==============================] - 0s 3ms/step - loss: 0.2376 - mean_absolute_error: 0.4351
Epoch 9/2000
4/4 [==============================] - 0s 3ms/step - loss: 0.2332 - mean_absolute_error: 0.4156
Epoch 10/2000
4/4 [

In [126]:
# 결과를 출력
print(model.weights)
print("test data [9,] 예측값 :", model.predict(test_data))

[<tf.Variable 'dense_1/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[1.9999993]], dtype=float32)>, <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32, numpy=array([-0.9999978], dtype=float32)>]
test data [9,] 예측값 : [[16.999996]]
